import { useState, useEffect, useRef, useCallback } from 'react'
import { supabase } from '../../lib/supabase'
import { useAuth } from '../../context/AuthContext'

// ── Section manifest ──────────────────────────────────────────────────────────
//   start / end are the literal markers Claude is instructed to wrap each section
const SECTIONS = [
  {
    key:   'cover_letter',
    label: 'Cover Letter',
    start: '[COVER_LETTER_START]',
    end:   '[COVER_LETTER_END]',
    hint:  'Letterhead, salutation, project overview, signature',
    pages: '1 page',
  },
  {
    key:   'executive_summary',
    label: 'Executive Summary',
    start: '[EXEC_SUMMARY_START]',
    end:   '[EXEC_SUMMARY_END]',
    hint:  'Goals, funding requested, expected outcomes',
    pages: '1 page',
  },
  {
    key:   'project_narrative',
    label: 'Project Narrative',
    start: '[PROJECT_NARRATIVE_START]',
    end:   '[PROJECT_NARRATIVE_END]',
    hint:  'Need, objectives, implementation plan, evaluation',
    pages: '2 pages',
  },
  {
    key:   'budget_justification',
    label: 'Budget Justification',
    start: '[BUDGET_START]',
    end:   '[BUDGET_END]',
    hint:  'Line-item budget with cost justifications by category',
    pages: '1–2 pages',
  },
  {
    key:   'signature_block',
    label: 'Signature Block',
    start: '[SIGNATURE_START]',
    end:   '[SIGNATURE_END]',
    hint:  'Certification statement, representative, contact details',
    pages: '1 page',
  },
]

const EMPTY_SECTIONS = Object.fromEntries(SECTIONS.map(s => [s.key, '']))

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Parse complete streamed text into per-section map */
function parseSections(fullText) {
  return Object.fromEntries(
    SECTIONS.map(({ key, start, end }) => {
      const s = fullText.indexOf(start)
      const e = fullText.indexOf(end)
      if (s === -1) return [key, '']
      return [key, fullText.slice(s + start.length, e === -1 ? fullText.length : e).trim()]
    })
  )
}

/** Derive which section is being generated and which are complete */
function getProgress(text) {
  let active = null
  const done = new Set()
  for (const { key, start, end } of SECTIONS) {
    if (text.includes(end))        done.add(key)
    else if (text.includes(start)) active = key
  }
  return { active, done }
}

/** Return the tail of the section currently being written (live preview) */
function getLivePreview(text, activeKey) {
  if (!activeKey) return ''
  const sec = SECTIONS.find(s => s.key === activeKey)
  if (!sec) return ''
  const idx = text.indexOf(sec.start)
  if (idx === -1) return ''
  const raw = text.slice(idx + sec.start.length)
  return raw.length > 320 ? '…' + raw.slice(-320) : raw
}

/** Word count for a text string */
function wc(text = '') {
  const t = text.trim()
  return t ? t.split(/\s+/).length : 0
}

// ── PDF export ────────────────────────────────────────────────────────────────
function exportPDF(sections, grantTitle) {
  const esc = (s = '') => String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')

  const sectionHtml = SECTIONS.map(({ key, label }, i) => `
    ${i > 0 ? '<div class="pb"></div>' : ''}
    <div class="sec">
      <h2>${esc(label)}</h2>
      <pre>${esc(sections[key] ?? '')}</pre>
    </div>`).join('')

  const html = `<!DOCTYPE html><html lang="en"><head>
<meta charset="UTF-8">
<title>${esc(grantTitle)} — Grant Proposal</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:'Times New Roman',Times,serif;padding:48px 56px;color:#111;max-width:860px;margin:auto;font-size:12pt}
  .title{font-size:17pt;font-weight:700;text-align:center;border-bottom:2.5px solid #0F1F3D;padding-bottom:10px;margin-bottom:6px}
  .subtitle{text-align:center;color:#555;font-size:9.5pt;margin-bottom:36px}
  h2{font-size:13pt;font-weight:700;color:#0F1F3D;border-bottom:1px solid #ccc;padding-bottom:4px;margin-bottom:14px;margin-top:28px}
  pre{font-family:inherit;line-height:1.75;white-space:pre-wrap;word-wrap:break-word}
  .sec{margin-bottom:32pt}
  .pb{page-break-before:always;height:0;border:none;margin:0}
  @media print{.pb{page-break-before:always;height:0}}
</style></head><body>
<p class="title">${esc(grantTitle)}</p>
<p class="subtitle">Grant Proposal · Generated by Q Analytics · ${new Date().toLocaleDateString('en-US',{dateStyle:'long'})}</p>
${sectionHtml}
</body></html>`

  const win = window.open('', '_blank')
  if (!win) { alert('Please allow pop-ups to export PDF.'); return }
  win.document.write(html)
  win.document.close()
  win.focus()
  // Small delay so styles are applied before print dialog opens
  setTimeout(() => { win.print() }, 500)
}

// ── Word export (lazy-loads docx + file-saver to keep initial bundle small) ───
async function exportWord(sections, grantTitle) {
  const [
    { Document, Packer, Paragraph, TextRun, HeadingLevel, PageBreak, AlignmentType },
    { saveAs },
  ] = await Promise.all([import('docx'), import('file-saver')])

  /** Split plain text into docx Paragraph children, preserving line breaks */
  const toParagraphs = (text = '') =>
    text.split('\n').map(line =>
      new Paragraph({
        children: [new TextRun({ text: line || ' ', size: 24, font: 'Times New Roman' })],
        spacing:  { after: 120 },
      })
    )

  const children = [
    // Document title
    new Paragraph({
      children: [new TextRun({ text: grantTitle, bold: true, size: 36, font: 'Times New Roman' })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 160 },
    }),
    new Paragraph({
      children: [new TextRun({
        text:  `Grant Proposal · Q Analytics · ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}`,
        size:  18, color: '666666', font: 'Times New Roman',
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 560 },
    }),
  ]

  SECTIONS.forEach(({ key, label }, i) => {
    if (i > 0) children.push(new Paragraph({ children: [new PageBreak()] }))
    children.push(
      new Paragraph({
        text: label,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 280, after: 240 },
      }),
      ...toParagraphs(sections[key])
    )
  })

  const doc = new Document({
    creator:     'Q Analytics',
    title:       grantTitle,
    description: 'Grant Proposal',
    sections: [{
      properties: {
        page: { margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } },
      },
      children,
    }],
  })

  const blob = await Packer.toBlob(doc)
  const safeName = grantTitle.replace(/[^a-zA-Z0-9\s-]/g, '').replace(/\s+/g, '_').slice(0, 60)
  saveAs(blob, `Grant_Proposal_${safeName}.docx`)
}

// ── Main component ────────────────────────────────────────────────────────────
export default function GrantWriter({ grant, onClose, onSaved }) {
  const { user } = useAuth()

  // Phase drives which view is rendered
  const [phase,      setPhase]      = useState('connecting') // connecting|generating|editing|error
  const [sections,   setSections]   = useState(EMPTY_SECTIONS)
  const [activeKey,  setActiveKey]  = useState('cover_letter')
  const [streamText, setStreamText] = useState('')
  const [progress,   setProgress]   = useState({ active: null, done: new Set() })
  const [saveStatus, setSaveStatus] = useState('idle')        // idle|saving|saved|error
  const [errorMsg,   setErrorMsg]   = useState('')
  const [exporting,  setExporting]  = useState(null)          // null|'pdf'|'word'
  const [retryKey,   setRetryKey]   = useState(0)             // increment to re-trigger generation

  // Raw accumulated stream text stored in a ref to avoid stale closure issues
  const streamRef     = useRef('')
  const textareaRefs  = useRef({})

  // ── Auto-start (or retry) generation ────────────────────────────────────────
  useEffect(() => {
    let cancelled = false
    streamRef.current = ''
    setStreamText('')
    setProgress({ active: null, done: new Set() })
    setPhase('connecting')

    async function generate() {
      try {
        const res = await fetch('/api/grant-writer', {
          method:  'POST',
          headers: { 'Content-Type': 'application/json' },
          body:    JSON.stringify({ user_id: user.id, grant_id: grant.id }),
        })

        if (!res.ok) {
          const err = await res.json().catch(() => ({}))
          throw new Error(err.error || `Server error ${res.status}`)
        }

        if (!cancelled) setPhase('generating')

        const reader  = res.body.getReader()
        const decoder = new TextDecoder()
        let   buffer  = ''

        while (true) {
          const { done, value } = await reader.read()
          if (done || cancelled) break

          buffer += decoder.decode(value, { stream: true })
          const lines = buffer.split('\n')
          buffer = lines.pop() ?? ''   // keep last (possibly incomplete) line

          for (const line of lines) {
            if (!line.startsWith('data: ')) continue
            try {
              const data = JSON.parse(line.slice(6))

              if (data.text) {
                streamRef.current += data.text
                const p = getProgress(streamRef.current)
                if (!cancelled) {
                  setStreamText(streamRef.current)
                  setProgress(p)
                }
              }

              if (data.done && !cancelled) {
                setSections(parseSections(streamRef.current))
                setActiveKey('cover_letter')
                setPhase('editing')
              }

              if (data.error) throw new Error(data.error)
            } catch (parseErr) {
              // Skip malformed SSE lines; rethrow real errors
              if (parseErr.message && !parseErr.message.startsWith('JSON')) throw parseErr
            }
          }
        }
      } catch (err) {
        if (!cancelled) {
          setErrorMsg(err.message || 'An unexpected error occurred.')
          setPhase('error')
        }
      }
    }

    generate()
    return () => { cancelled = true }
  }, [retryKey])   // retryKey increment re-triggers the effect

  // ── Auto-resize textarea when active section changes ─────────────────────────
  useEffect(() => {
    const el = textareaRefs.current[activeKey]
    if (el) {
      el.style.height = 'auto'
      el.style.height = `${el.scrollHeight}px`
    }
  }, [activeKey, sections])

  // ── Prevent body scroll while modal is open ───────────────────────────────────
  useEffect(() => {
    document.body.style.overflow = 'hidden'
    return () => { document.body.style.overflow = '' }
  }, [])

  // ── Save draft to grant_proposals ────────────────────────────────────────────
  const saveDraft = useCallback(async () => {
    setSaveStatus('saving')
    try {
      const content = JSON.stringify(sections)

      // Check for existing draft (upsert pattern)
      const { data: existing } = await supabase
        .from('grant_proposals')
        .select('id')
        .eq('agency_id', user.id)
        .eq('grant_id', grant.id)
        .maybeSingle()

      if (existing?.id) {
        const { error } = await supabase
          .from('grant_proposals')
          .update({ draft_content: content, status: 'draft' })
          .eq('id', existing.id)
        if (error) throw error
      } else {
        const { error } = await supabase.from('grant_proposals').insert({
          agency_id:     user.id,
          grant_id:      grant.id,
          draft_content: content,
          status:        'draft',
        })
        if (error) throw error
      }

      setSaveStatus('saved')
      onSaved?.()
      setTimeout(() => setSaveStatus('idle'), 3500)
    } catch (err) {
      console.error('Save draft failed:', err)
      setSaveStatus('error')
      setTimeout(() => setSaveStatus('idle'), 3500)
    }
  }, [sections, user.id, grant.id, onSaved])

  // ── Export handlers ───────────────────────────────────────────────────────────
  function handleExportPDF() {
    setExporting('pdf')
    exportPDF(sections, grant.grant_title)
    setTimeout(() => setExporting(null), 1000)
  }

  async function handleExportWord() {
    setExporting('word')
    try {
      await exportWord(sections, grant.grant_title)
    } catch (err) {
      console.error('Word export failed:', err)
      alert('Word export failed. Please try again.')
    } finally {
      setExporting(null)
    }
  }

  // ── Current section index (for Prev/Next navigation) ─────────────────────────
  const activeIdx = SECTIONS.findIndex(s => s.key === activeKey)
  const totalWords = SECTIONS.reduce((sum, s) => sum + wc(sections[s.key]), 0)

  // ════════════════════════════════════════════════════════════════════════════
  // PHASE: connecting
  // ════════════════════════════════════════════════════════════════════════════
  if (phase === 'connecting') {
    return (
      <div className="fixed inset-0 z-50 bg-navy-900 flex items-center justify-center">
        <div className="text-center space-y-4">
          <div className="w-14 h-14 border-4 border-white/30 border-t-white rounded-full animate-spin mx-auto" />
          <p className="text-white font-bold text-lg">Loading Grant Writer…</p>
          <p className="text-blue-200 text-sm">Fetching agency profile and grant details</p>
        </div>
      </div>
    )
  }

  // ════════════════════════════════════════════════════════════════════════════
  // PHASE: error
  // ════════════════════════════════════════════════════════════════════════════
  if (phase === 'error') {
    return (
      <div className="fixed inset-0 z-50 bg-navy-900/90 backdrop-blur-sm flex items-center justify-center p-4">
        <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-md w-full text-center">
          <div className="w-14 h-14 bg-red-50 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg className="w-7 h-7 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                d="M12 9v2m0 4h.01M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/>
            </svg>
          </div>
          <h2 className="text-lg font-bold text-gray-900 mb-2">Generation Failed</h2>
          <p className="text-sm text-gray-500 mb-6 leading-relaxed">{errorMsg}</p>
          <div className="flex gap-3">
            <button onClick={onClose}
              className="flex-1 px-4 py-2.5 text-sm border border-gray-200 rounded-xl
                text-gray-600 hover:bg-gray-50 transition-colors font-medium">
              Close
            </button>
            <button
              onClick={() => { setErrorMsg(''); setRetryKey(k => k + 1) }}
              className="flex-1 px-4 py-2.5 text-sm bg-navy-900 text-white rounded-xl
                hover:bg-navy-800 transition-colors font-semibold">
              Try Again
            </button>
          </div>
        </div>
      </div>
    )
  }

  // ════════════════════════════════════════════════════════════════════════════
  // PHASE: generating — full-screen dark view with live progress sidebar
  // ════════════════════════════════════════════════════════════════════════════
  if (phase === 'generating') {
    const livePreview   = getLivePreview(streamText, progress.active)
    const activeSection = SECTIONS.find(s => s.key === progress.active)

    return (
      <div className="fixed inset-0 z-50 bg-navy-900 flex flex-col">
        {/* Header */}
        <div className="flex items-center gap-4 px-6 py-4 border-b border-white/10">
          <div className="flex items-center gap-3 flex-1 min-w-0">
            <div className="relative flex-shrink-0">
              <div className="w-8 h-8 border-[3px] border-white/20 border-t-white rounded-full animate-spin" />
              <div className="absolute inset-0 flex items-center justify-center">
                <div className="w-2 h-2 bg-blue-400 rounded-full opacity-70" />
              </div>
            </div>
            <div className="min-w-0">
              <p className="text-white font-bold text-sm leading-tight">Writing Grant Proposal</p>
              <p className="text-blue-300 text-xs truncate">{grant.grant_title}</p>
            </div>
          </div>
          <button onClick={onClose}
            className="text-white/40 hover:text-white/80 text-sm transition-colors flex-shrink-0">
            Cancel
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 flex overflow-hidden">

          {/* ── Progress sidebar ── */}
          <div className="w-56 border-r border-white/10 p-5 flex-shrink-0 hidden sm:flex flex-col">
            <p className="text-white/40 text-xs font-semibold uppercase tracking-wider mb-4">
              Sections
            </p>
            <ol className="space-y-3 flex-1">
              {SECTIONS.map(({ key, label, pages }) => {
                const isDone    = progress.done.has(key)
                const isWriting = progress.active === key
                return (
                  <li key={key} className="flex items-start gap-2.5">
                    {/* Status indicator */}
                    <div className={`mt-0.5 w-5 h-5 rounded-full flex-shrink-0 flex items-center
                        justify-center border-2 transition-colors
                        ${isDone    ? 'bg-green-500 border-green-500' :
                          isWriting ? 'border-blue-400 bg-transparent' :
                                      'border-white/20 bg-transparent'}`}>
                      {isDone && (
                        <svg className="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7"/>
                        </svg>
                      )}
                      {isWriting && <div className="w-2 h-2 bg-blue-400 rounded-full animate-pulse"/>}
                    </div>
                    <div className="min-w-0">
                      <p className={`text-xs font-medium leading-tight
                        ${isDone ? 'text-green-300' : isWriting ? 'text-white' : 'text-white/30'}`}>
                        {label}
                      </p>
                      <p className={`text-xs mt-0.5 ${isDone || isWriting ? 'text-white/40' : 'text-white/15'}`}>
                        {pages}
                      </p>
                    </div>
                  </li>
                )
              })}
            </ol>
            <div className="pt-4 border-t border-white/10">
              <p className="text-white/30 text-xs">
                {progress.done.size}/{SECTIONS.length} sections complete
              </p>
            </div>
          </div>

          {/* ── Live writing preview ── */}
          <div className="flex-1 flex flex-col p-5 overflow-hidden">
            <div className="flex items-center gap-2 mb-3 flex-shrink-0">
              {activeSection ? (
                <>
                  <span className="inline-block w-2 h-2 bg-blue-400 rounded-full animate-pulse"/>
                  <p className="text-blue-300 text-xs font-medium">
                    Writing: {activeSection.label}
                  </p>
                </>
              ) : (
                <p className="text-white/30 text-xs">Initializing…</p>
              )}
            </div>

            {/* Streaming text window */}
            <div className="flex-1 bg-white/5 rounded-xl border border-white/10 p-5 overflow-y-auto">
              {livePreview ? (
                <p className="text-white/75 text-sm leading-relaxed font-mono whitespace-pre-wrap break-words">
                  {livePreview}
                  {/* Blinking cursor */}
                  <span className="inline-block w-[2px] h-[14px] bg-blue-400 ml-0.5 align-middle animate-pulse"/>
                </p>
              ) : (
                <div className="h-full flex items-center justify-center">
                  <p className="text-white/20 text-sm">
                    Claude is reading your agency profile…
                  </p>
                </div>
              )}
            </div>

            <p className="text-white/20 text-xs mt-3 text-right flex-shrink-0">
              Powered by Claude Opus with adaptive intelligence · Do not close this window
            </p>
          </div>
        </div>
      </div>
    )
  }

  // ════════════════════════════════════════════════════════════════════════════
  // PHASE: editing — full-screen editor with sidebar nav
  // ════════════════════════════════════════════════════════════════════════════
  const activeSec = SECTIONS[activeIdx]

  return (
    <div className="fixed inset-0 z-50 bg-gray-100 flex flex-col">

      {/* ── Toolbar ── */}
      <div className="bg-navy-900 text-white px-4 sm:px-5 py-3 flex items-center gap-2 sm:gap-3
                      flex-shrink-0 shadow-lg">
        <button
          onClick={onClose}
          className="flex items-center gap-1.5 text-white/60 hover:text-white text-sm
                     transition-colors flex-shrink-0 mr-1"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
              d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
          </svg>
          <span className="hidden sm:inline text-sm font-medium">Back</span>
        </button>

        <div className="flex-1 min-w-0">
          <p className="text-[10px] text-white/40 uppercase tracking-widest font-semibold">
            Grant Writer
          </p>
          <p className="text-sm font-bold truncate leading-tight">{grant.grant_title}</p>
        </div>

        {/* Action buttons */}
        <div className="flex items-center gap-1.5 sm:gap-2 flex-shrink-0">

          {/* Save Draft */}
          <button
            onClick={saveDraft}
            disabled={saveStatus === 'saving'}
            className={`flex items-center gap-1.5 px-2.5 sm:px-3 py-1.5 rounded-lg
              text-xs font-semibold transition-all duration-200
              ${saveStatus === 'saved'
                ? 'bg-green-500 text-white'
                : saveStatus === 'error'
                ? 'bg-red-500 text-white'
                : saveStatus === 'saving'
                ? 'bg-white/10 text-white/40 cursor-wait'
                : 'bg-white/10 hover:bg-white/20 text-white'}`}
          >
            {saveStatus === 'saving' ? (
              <>
                <div className="w-3 h-3 border-[2px] border-white/40 border-t-white rounded-full animate-spin"/>
                <span className="hidden sm:inline">Saving…</span>
              </>
            ) : saveStatus === 'saved' ? (
              <>
                <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7"/>
                </svg>
                <span className="hidden sm:inline">Saved</span>
              </>
            ) : saveStatus === 'error' ? (
              <span>Failed</span>
            ) : (
              <>
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                    d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4"/>
                </svg>
                <span className="hidden sm:inline">Save Draft</span>
              </>
            )}
          </button>

          {/* Export PDF */}
          <button
            onClick={handleExportPDF}
            disabled={!!exporting}
            className="flex items-center gap-1.5 px-2.5 sm:px-3 py-1.5
              bg-white/10 hover:bg-white/20 rounded-lg text-xs font-semibold
              text-white transition-colors disabled:opacity-40"
          >
            {exporting === 'pdf' ? (
              <div className="w-3 h-3 border-[2px] border-white/40 border-t-white rounded-full animate-spin"/>
            ) : (
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"/>
              </svg>
            )}
            <span className="hidden sm:inline">{exporting === 'pdf' ? 'Exporting…' : 'PDF'}</span>
          </button>

          {/* Export Word */}
          <button
            onClick={handleExportWord}
            disabled={!!exporting}
            className="flex items-center gap-1.5 px-2.5 sm:px-3 py-1.5
              bg-blue-600 hover:bg-blue-500 rounded-lg text-xs font-semibold
              text-white transition-colors disabled:opacity-40"
          >
            {exporting === 'word' ? (
              <div className="w-3 h-3 border-[2px] border-white/40 border-t-white rounded-full animate-spin"/>
            ) : (
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0
                     01.707.293l5.414 5.414A1 1 0 0119 9.414V19a2 2 0 01-2 2z"/>
              </svg>
            )}
            <span className="hidden sm:inline">{exporting === 'word' ? 'Exporting…' : 'Word'}</span>
          </button>
        </div>
      </div>

      {/* ── Mobile section tabs (visible below lg) ── */}
      <div className="lg:hidden bg-white border-b border-gray-200 overflow-x-auto flex-shrink-0">
        <div className="flex gap-0">
          {SECTIONS.map(({ key, label }) => (
            <button
              key={key}
              onClick={() => setActiveKey(key)}
              className={`flex-shrink-0 px-4 py-2.5 text-xs font-semibold border-b-2 transition-colors
                whitespace-nowrap
                ${activeKey === key
                  ? 'border-navy-900 text-navy-900 bg-blue-50'
                  : 'border-transparent text-gray-500 hover:text-gray-700'}`}
            >
              {label}
            </button>
          ))}
        </div>
      </div>

      {/* ── Main layout ── */}
      <div className="flex-1 flex overflow-hidden">

        {/* Sidebar (desktop only) */}
        <aside className="hidden lg:flex w-56 bg-white border-r border-gray-200 flex-col flex-shrink-0">
          <div className="px-4 py-3 border-b border-gray-100">
            <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Sections</p>
          </div>

          <nav className="flex-1 p-2 overflow-y-auto">
            {SECTIONS.map(({ key, label, hint, pages }) => {
              const count = wc(sections[key])
              return (
                <button
                  key={key}
                  onClick={() => setActiveKey(key)}
                  className={`w-full text-left px-3 py-3 rounded-lg mb-1 transition-all group
                    ${activeKey === key
                      ? 'bg-navy-900 text-white shadow-sm'
                      : 'hover:bg-gray-50 text-gray-700'}`}
                >
                  <div className="flex items-start justify-between gap-2">
                    <span className="text-xs font-semibold leading-tight">{label}</span>
                    <span className={`text-xs flex-shrink-0 font-mono
                      ${activeKey === key ? 'text-white/50' : 'text-gray-300'}`}>
                      {count > 0 ? `${count}w` : pages}
                    </span>
                  </div>
                  <p className={`text-xs mt-1 leading-tight line-clamp-2
                    ${activeKey === key ? 'text-white/60' : 'text-gray-400'}`}>
                    {hint}
                  </p>
                </button>
              )
            })}
          </nav>

          {/* Sidebar footer */}
          <div className="px-4 py-3 border-t border-gray-100 space-y-1">
            <p className="text-xs text-gray-500">
              <span className="font-semibold text-gray-700">{totalWords.toLocaleString()}</span> total words
            </p>
            <div className="flex gap-1">
              {SECTIONS.map(({ key }) => (
                <div key={key}
                  className={`flex-1 h-1 rounded-full transition-colors
                    ${wc(sections[key]) > 0 ? 'bg-green-400' : 'bg-gray-200'}`}
                />
              ))}
            </div>
          </div>
        </aside>

        {/* ── Editor pane ── */}
        <main className="flex-1 overflow-y-auto">
          <div className="max-w-4xl mx-auto px-4 sm:px-8 py-6">

            {/* Section header */}
            <div className="mb-5 flex items-start justify-between gap-4">
              <div>
                <h2 className="text-xl font-bold text-navy-900">{activeSec.label}</h2>
                <p className="text-sm text-gray-400 mt-0.5">{activeSec.hint} · {activeSec.pages}</p>
              </div>
              <span className="text-xs bg-navy-900/5 text-navy-900 font-semibold px-3 py-1
                rounded-full border border-navy-900/10 flex-shrink-0">
                {wc(sections[activeKey]).toLocaleString()} words
              </span>
            </div>

            {/* Editable section card */}
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
              <textarea
                ref={el => { textareaRefs.current[activeKey] = el }}
                key={activeKey}   /* remount on section change to reset scroll position */
                value={sections[activeKey] ?? ''}
                onChange={e => {
                  setSections(prev => ({ ...prev, [activeKey]: e.target.value }))
                  // Auto-resize
                  e.target.style.height = 'auto'
                  e.target.style.height = `${e.target.scrollHeight}px`
                }}
                placeholder={`Start writing the ${activeSec.label} here…`}
                spellCheck
                className="w-full p-6 sm:p-8 text-gray-800 text-sm leading-relaxed
                  font-mono focus:outline-none resize-none min-h-[480px] bg-white
                  placeholder:text-gray-300"
              />

              {/* Textarea footer */}
              <div className="px-6 sm:px-8 py-3 bg-gray-50 border-t border-gray-100
                              flex items-center justify-between gap-4">
                <p className="text-xs text-gray-400 tabular-nums">
                  {wc(sections[activeKey]).toLocaleString()} words ·&nbsp;
                  {(sections[activeKey] ?? '').length.toLocaleString()} characters
                </p>
                <div className="flex items-center gap-3">
                  {activeIdx > 0 && (
                    <button
                      onClick={() => setActiveKey(SECTIONS[activeIdx - 1].key)}
                      className="text-xs text-gray-400 hover:text-gray-700 transition-colors font-medium"
                    >
                      ← {SECTIONS[activeIdx - 1].label}
                    </button>
                  )}
                  {activeIdx < SECTIONS.length - 1 && (
                    <button
                      onClick={() => setActiveKey(SECTIONS[activeIdx + 1].key)}
                      className="text-xs text-blue-500 hover:text-blue-700 transition-colors font-semibold"
                    >
                      {SECTIONS[activeIdx + 1].label} →
                    </button>
                  )}
                </div>
              </div>
            </div>

            {/* Grant context card — reference while editing */}
            <div className="mt-5 bg-blue-50 border border-blue-100 rounded-xl p-4">
              <p className="text-xs font-bold text-blue-800 mb-2 uppercase tracking-wider">
                Grant Reference
              </p>
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-6 gap-y-1.5 text-xs text-blue-700">
                {grant.deadline && (
                  <div>
                    <span className="text-blue-400">Deadline</span>
                    <span className="ml-2 font-semibold">
                      {new Date(grant.deadline).toLocaleDateString('en-US', {
                        month: 'short', day: 'numeric', year: 'numeric',
                      })}
                    </span>
                  </div>
                )}
                {(grant.amount_min || grant.amount_max) && (
                  <div>
                    <span className="text-blue-400">Amount</span>
                    <span className="ml-2 font-semibold">
                      {[grant.amount_min, grant.amount_max]
                        .filter(Boolean)
                        .map(v => `$${Number(v).toLocaleString()}`)
                        .join(' – ')}
                    </span>
                  </div>
                )}
                {grant.source_url && (
                  <div>
                    <a
                      href={grant.source_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-blue-600 hover:underline font-semibold"
                    >
                      View Original ↗
                    </a>
                  </div>
                )}
              </div>
              {grant.qualify_reason && (
                <p className="text-xs text-blue-600 mt-2 leading-relaxed italic">
                  {grant.qualify_reason}
                </p>
              )}
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}
